[package]
name = "timetrackrs"
version = "0.1.0"
authors = ["phiresky <phireskyde+git@gmail.com>"]
edition = "2018"
license = "AGPL-3.0-or-later"


[dependencies]
anyhow = "1.0.48"
byteorder = "1.4.3"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = { version = "1.0.72", features = ["preserve_order"] }
hex = "0.4.3"
sysinfo = "0.23.0"
chrono = { version = "0.4.19", features = ["serde"] }
dotenv = "0.15.0"
rand = "0.8.4"
typescript-definitions = { git = "https://github.com/onelson/typescript-definitions", branch = "no-debug-attrs"}

lazy_static = "1.4.0"

uuid = { version = "0.8.2", features = ["serde", "v4"] }
regex = "1.5.4"
battery = "0.7.8"
os_info = "3.0.8"
url = "2.2.2"
structopt = "0.3.25"
base64 = "0.13.0"
rust-crypto = "0.2.36"
rsa = "0.5.0"
openssl = "0.10.38"
tar = "0.4.37"
bzip2 = "0.4.3"
enum-utils = "0.1.2"
num_enum = "0.5.4"
enum_dispatch = "0.3.7"
zstd = "0.9.0"
tempfile = "3.2.0"
concat-reader = "0.1.0"
yup-oauth2 = "6.0.0"
hyper = "0.14.15"
hyper-rustls = "0.23.0"
hyper-tls = "0.5.0"
futures = "0.3.18"
csv = "1.1.6"
chrono-tz = "0.6.0"
zip = "0.5.13"
youtube_dl = "0.7.0"
derive_more = "0.99.16"
directories-next = "2.0.0"
serde_regex = "1.1.0"
mediawiki = "0.2.7"
itertools = "0.10.1"
datachannel = { version = "0.7.2", features = ["static"], optional = true }
tokio = { version = "1.14.0", features = ["full"] }
tungstenite = "0.16.0"
futures-util = "0.3.18"
futures-channel = "0.3.18"
tokio-tungstenite = "0.16.0"
async-channel = "1.6.1"
whoami = "1.2.1"
multimap = "0.8.3"
paste = "1.0.6"
lru = { version = "0.7.0", features = ["nightly"] } # https://github.com/jeromefroe/lru-rs/pull/40
owning_ref = "0.4.1"
rust-embed = { version = "6.2.0", features = ["compression"] }
sqlx = { version = "0.5.1", features = ["sqlite", "any", "runtime-tokio-native-tls", "json"], git="https://github.com/phiresky/sqlx" }
warp = { version = "0.3.2", features = ["compression"] }
mime_guess = "2.0.3"
async-trait = "0.1.51"
ansi-escapes = "0.1.1"
tokio-stream = { version = "0.1.8", features = ["sync"] }
tokio-timer = "0.2.13"
addr = "0.15.1"
crc32fast = "1.2.2"
gethostname = "0.2.1"
md5 = "0.7.0"
wmi = "0.9.2"
user-idle = "0.5.0"
env_logger = "0.9.0"
tracing = { version = "0.1.29", features = ["log"] }
tracing-appender = "0.2.0"
tracing-subscriber = { version = "0.3.3", features = ["env-filter"] }
rustc-hash = "1.1.0"
graphql_client = "0.10.0"
reqwest = {version = "0.11.9", features = ["json"]}

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.9", features = ["winuser", "processthreadsapi","handleapi", "psapi"] }

[target.'cfg(target_os="linux")'.dependencies]
x11rb = { version = "0.9.0", features = ["screensaver"] }
xcb = "0.10.1"
nl80211 = {git="https://github.com/Eonm/nl80211", branch="master"}

[target.'cfg(target_os = "macos")'.dependencies]
objc = "0.2.7"
libc = "0.2.113"
core-graphics = "0.22.3"
core-foundation = "0.9.2"

[features]
sync = ["datachannel"]
openssl-vendored = ["openssl/vendored"]

[profile.dev.package."*"]
opt-level = 3

#lto="fat"
[profile.release]
debug = true # keep debug info in release build


[[bin]]
name = "trbtt-sync"
required-features = ["sync"]

[[bin]]
name = "trbtt-signalling-server"
required-features = ["sync"]
